package civ

import civ.ai.AiType
import civ.core.GameState
import civ.hex.Coordinates
import civ.tile.Grass
import civ.hex.HexLayouts
import civ.hex.MapGenerator
import civ.hex.neighbors
import civ.hex.toCoordinates
import civ.model.*
import civ.tile.Mountains
import civ.tile.Water
import kotlin.js.ExperimentalJsExport
import kotlin.js.JsExport
import kotlin.random.Random

@OptIn(ExperimentalJsExport::class)
@JsExport
object TestData {
//
//    val cityCoords = Coordinates(1, 1)
//
//    val map1 = HexLayouts.rectangle(10, 10)
//        .map {
//            Grass(it, buildings = if (it == cityCoords) setOf(Building.VILLAGE_HALL) else setOf())
//        }
//        .toSet()
//
//    val differentTerrainsMap by lazy {
//        val base = HexLayouts.rectangle(10, 10)
//        base.map { coords ->
//            if (coords.neighbors().count { base.contains(it) } != 6)
//                return@map Water(coords)
//
//            if (coords in arrayOf(5 to 1, 5 to 2, 4 to 2).map { it.toCoordinates() }) {
//                return@map Grass(coords, forest = true)
//            }
//
//            if (coords in arrayOf(5 to 4).map { it.toCoordinates() }) {
//                return@map Grass(coords, forest = true, animals = true)
//            }
//
//            if (coords in arrayOf(6 to 4).map { it.toCoordinates() }) {
//                return@map Grass(coords, forest = false, animals = true)
//            }
//
//            if (coords in arrayOf(2 to 6).map { it.toCoordinates() }) {
//                return@map Mountains(coords, gold = false)
//            }
//
//            if (coords in arrayOf(3 to 6).map { it.toCoordinates() }) {
//                return@map Mountains(coords, gold = true)
//            }
//
//            Grass(coords, buildings = if (coords == cityCoords) setOf(Building.VILLAGE_HALL) else setOf())
//        }
//            .toSet()
//    }
//
//    val gameState1 by lazy {
//        val playerList = listOf(
//            Player(name = "Pierwszy", color = PlayerColor.BLUE),
//            Player(name = "Drugi", color = PlayerColor.RED),
//        )
//
//        val unitCoords = mutableListOf(
//            Coordinates(1, 2),
//            Coordinates(2, 1),
//            Coordinates(3, 3),
//            Coordinates(4, 4),
//        )//map1.toMutableList().also { it.shuffle() }
//
//        GameState(
//            players = playerList,
//            tileList = map1.map { if (it.coords in unitCoords) it.updated(isBusy = true) else it }.toSet(),
//            cities = setOf(
//                City(
//                    coordinates = cityCoords,
//                    playerId = playerList[0].playerId,
//                )
//            ),
//            units = playerList.flatMapTo(mutableSetOf()) {
//                listOf(
//                    CivUnit(
//                        unitType = UnitType.SETTLERS,
//                        playerId = it.playerId,
//                        coordinates = unitCoords.removeFirst(),
//                    ),
//                    CivUnit(
//                        unitType = UnitType.SCOUT,
//                        playerId = it.playerId,
//                        coordinates = unitCoords.removeFirst(),
//                    )
//                )
//            },
//            stock = playerList.associate { it.playerId to Stockpiles(50, 50, 50) },
//        )
//    }
//
//
//    val gameState2 by lazy {
//        val playerList = listOf(
//            Player(name = "Pierwszy", color = PlayerColor.BLUE),
//            Player(name = "Drugi", color = PlayerColor.RED),
//        )
//
//        val unitCoords = mutableListOf(
//            Coordinates(1, 2),
//            Coordinates(2, 1),
//            Coordinates(3, 3),
//            Coordinates(4, 4),
//        )
//
//        GameState(
//            players = playerList,
//            tileList = differentTerrainsMap.map { if (it.coords in unitCoords) it.updated(isBusy = true) else it }
//                .toSet(),
//            cities = setOf(
//                City(
//                    coordinates = cityCoords,
//                    playerId = playerList[0].playerId,
//                )
//            ),
//            units = playerList.flatMapTo(mutableSetOf()) {
//                listOf(
//                    CivUnit(
//                        unitType = UnitType.SETTLERS,
//                        playerId = it.playerId,
//                        coordinates = unitCoords.removeFirst(),
//                    ),
//                    CivUnit(
//                        unitType = UnitType.SCOUT,
//                        playerId = it.playerId,
//                        coordinates = unitCoords.removeFirst(),
//                    )
//                )
//            },
//            stock = playerList.associate { it.playerId to Stockpiles(50, 50, 50) },
//        )
//    }
//
//    //seeds
//    // Seed: -4945819805719851227
//    val generated by lazy {
//        val playerList = listOf(
////            Player(name = "Pierwszy", color = PlayerColor.BLUE),
////            Player(name = "Drugi", color = PlayerColor.RED),
//            Player(name = "Pierwszy", color = PlayerColor.BLUE),
//            Player(name = "Drugi", color = PlayerColor.RED, aiType = AiType.OTP_ARCHER),
//            Player(name = "Trzeci", color = PlayerColor.GREEN, aiType = AiType.OTP_WARRIOR),
////            Player(name = "Czwarty", color = PlayerColor.YELLOW, aiType = AiType.OTP_SCOUT),
//        )
//
////        val seed = -4945819805719851227
//        val seed = Random.nextLong()
//        println("Seed: $seed")
//
//        val mapData =  MapGenerator(seed).generate(20, 20, players = playerList)
//
//        GameState(
//            players = playerList,
//            tileList = mapData.tiles,
//            cities = setOf(),
//            units =  mapData.units.mapTo(mutableSetOf()) { entry ->
//                CivUnit(
//                    coordinates = entry.key,
//                    playerId = entry.value.first,
//                    unitType = entry.value.second,
//                )
//            },
//            stock = playerList.associate { it.playerId to Stockpiles(50, 50, 50) },
//        )
//    }
//
}
